name = "KyotoCabinet"
uuid = "5d459dcf-b23e-42b3-938d-072f208f6c69"
authors = ["Dmitry aka tuzzeng", "Evgeny Cherkashin <eugeneai@irnok.net>"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
